# AUTOSTART
exec-once = $terminal
exec-once = hyprpm reload -n
exec-once = hyprctl reload
exec-once = waybar
exec-once = hypridle
# exec-once = systemctl --user start hyprpolkitagent
exec-once = awww-daemon &
exec-once = awww img ~/Imágenes/wallpaper-hyperland/Kath.png
exec-once = xrdb ~/.Xresources
exec-once = snappy-switcher --daemon
exec-once = $nwg-drawer -r -wm hyprland -i Papirus
exec-once = swaync
exec-once = sysauth
