# KEYBINDINGS GENERALES
$mainMod = SUPER

bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, exec,/home/notlim_dev/.config/hypr/scripts/hypr-confirm-close
bind = $mainMod, N, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, F, togglefloating,
bind = $mainMod, Space, exec, $menu

# preview workspace panels grid
bind = $mainMod,g,hyprexpo:expo,toggle

bind = $mainMod, b,exec, $browser
bind = $mainMod ALT, P,exec, wlogout
bind = $mainMod, C,exec, hyprpicker -a

# Abrir terminal flotante con dimensiones especificas
bind = $mainMod ALT, Return,exec, kitty --class floatterm

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod ALT, mouse:272, resizewindow

# Resize
bind = CTRL SHIFT ALT, left, resizeactive, 5 0
bind = CTRL SHIFT ALT, right, resizeactive, -5 0
bind = CTRL SHIFT ALT, up, resizeactive, 0 5
bind = CTRL SHIFT ALT, down, resizeactive, 0 -5

# Fullscreen
bind = $mainMod, M, fullscreen, 1

# Screenshot
bind = SUPER ALT, S, exec, quickshell -c HyprQuickFrame -n

# Alt-Tab to cycle windows
bind = ALT, Tab, exec, snappy-switcher next
bind = ALT SHIFT, Tab, exec, snappy-switcher prev
