# KEYMAPS HY3
# Se cargan desde ~/.config/hypr/hy3.conf

# Atajos hy3
bind = $mainMod, Z, hy3:killactive

# Crear splits
bind = $mainMod, v, hy3:makegroup, v
bind = $mainMod, h, hy3:makegroup, h
bind = $mainMod, x, hy3:makegroup, h, toggle

# Cambiar flujo de splits
bind = $mainMod, O, hy3:changegroup, opposite

# Pestañas
bind = $mainMod, T, hy3:makegroup, tab
bind = $mainMod, Tab, hy3:focustab, r, wrap
bind = $mainMod SHIFT, T, hy3:changegroup, toggletab

# Cambiar foco entre capa flotante/tiling
bind = $mainMod, y, hy3:togglefocuslayer

# Navegar foco (arbol hy3)
bind = $mainMod, left, hy3:movefocus, l
bind = $mainMod, right, hy3:movefocus, r
bind = $mainMod, up, hy3:movefocus, u
bind = $mainMod, down, hy3:movefocus, d

bind = $mainMod SHIFT, h, hy3:movefocus, l, visible, nowarp
bind = $mainMod SHIFT, j, hy3:movefocus, d, visible, nowarp
bind = $mainMod SHIFT, k, hy3:movefocus, u, visible, nowarp
bind = $mainMod SHIFT, l, hy3:movefocus, r, visible, nowarp
bind = $mainMod SHIFT, left, hy3:movefocus, l, visible
bind = $mainMod SHIFT, down, hy3:movefocus, d, visible
bind = $mainMod SHIFT, up, hy3:movefocus, u, visible
bind = $mainMod SHIFT, right, hy3:movefocus, r, visible

# Mover ventanas dentro del arbol
bind = $mainMod+SHIFT+CONTROL, h, hy3:movewindow, l, once
bind = $mainMod+SHIFT+CONTROL, j, hy3:movewindow, d, once
bind = $mainMod+SHIFT+CONTROL, k, hy3:movewindow, u, once
bind = $mainMod+SHIFT+CONTROL, l, hy3:movewindow, r, once
bind = $mainMod+SHIFT+CONTROL, left, hy3:movewindow, l, once
bind = $mainMod+SHIFT+CONTROL, right, hy3:movewindow, r, once
bind = $mainMod+SHIFT+CONTROL, up, hy3:movewindow, u, once
bind = $mainMod+SHIFT+CONTROL, down, hy3:movewindow, d, once

bind = $mainMod+CONTROL, h, hy3:movewindow, l, once, visible
bind = $mainMod+CONTROL, j, hy3:movewindow, d, once, visible
bind = $mainMod+CONTROL, k, hy3:movewindow, u, once, visible
bind = $mainMod+CONTROL, l, hy3:movewindow, r, once, visible
bind = $mainMod+CONTROL, left, hy3:movewindow, l, once, visible
bind = $mainMod+CONTROL, down, hy3:movewindow, d, once, visible
bind = $mainMod+CONTROL, up, hy3:movewindow, u, once, visible
bind = $mainMod+CONTROL, right, hy3:movewindow, r, once, visible
