# WINDOW RULES
# windowrule = opacity 0.9 0.9, match:class kitty
windowrule = no_blur on, match:class kitty
windowrule = opacity 0.95 0.95, match:class obsidian
windowrule = opacity 0.9 0.9, match:class floatterm
windowrule = opacity 0.9 0.9, match:class XTerm
windowrule = no_blur on,opacity 0.9 0.9, match:class Alacritty

windowrule {
    name = floating terminal
    match:class = floatterm
    float = yes
}

windowrule {
    name = mpv floating
    match:class = mpv
    float = yes
    center = yes
    size = 960 540
}

windowrule {
    name = firefox floating
    match:class = firefox
    float = yes
    center = yes
    size = 960 540
}

windowrule {
    name = chromium floating
    match:class = chromium
    float = yes
    center = yes
    size = 960 540
}

windowrule {
    name = xterm floating
    match:class = XTerm
    float = yes
    center = yes
    size = 960 540
}

windowrule {
    name = ueberzugpp preview
    match:class = ^ueberzugpp_.*
    float = yes
    # pin = yes
    no_initial_focus = yes
}
