#.·:'''''''''''''''''''''''''''''''''''''''''''''''''''':·.
#: : ┌┬┐┌─┐┌┬┐┌─┐┬┬  ┌─┐┌─┐  ┌┐┌┌─┐┌┬┐┬  ┬┌┬┐┌┬┐┌─┐┬  ┬ : :
#: :  │││ │ │ ├┤ ││  ├┤ └─┐  ││││ │ │ │  ││││ ││├┤ └┐┌┘ : :
#: : ─┴┘└─┘ ┴ └  ┴┴─┘└─┘└─┘  ┘└┘└─┘ ┴ ┴─┘┴┴ ┴─┴┘└─┘ └┘  : :
#'·:....................................................:·'

############################
### HYPRLAND MODULAR CONF ###
############################

# Core
source = ~/.config/hypr/modulos/monitores.conf
source = ~/.config/hypr/modulos/programas.conf
source = ~/.config/hypr/modulos/autostart.conf
source = ~/.config/hypr/modulos/entorno.conf

# Look and feel
source = ~/.config/hypr/modulos/general.conf
source = ~/.config/hypr/modulos/decoracion.conf
source = ~/.config/hypr/modulos/animaciones.conf
source = ~/.config/hypr/modulos/layouts.conf

# Input and binds
source = ~/.config/hypr/modulos/input.conf
source = ~/.config/hypr/modulos/keybindings.conf
source = ~/.config/hypr/modulos/keymaps-nativos.conf
source = ~/.config/hypr/modulos/teclas-multimedia.conf

# Windows
source = ~/.config/hypr/modulos/windowrules.conf

# Plugin hy3 (opcional, desactivado por update)
# Si lo activas, comenta keymaps-nativos.conf para evitar conflicto de atajos.
# source = ~/.config/hypr/hy3.conf
